before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script: gulp travis

language: node_js
node_js:
  - '6.9.2'

# Disable email notifications
notifications:  
  email: false